language: ruby
rvm:
- 2.0.0
- 2.1.2
script: bundle exec rspec
branches:
  only:
  - master
notifications:
  email: false
  slack:
    secure: HKvrZjP1KUWhyNMA/3TfIe7vGXARu0gZFnntYPpIGm0N3Y8o3IHBc0Z0cY6N/VpFLinA95mfG8fk6SWUyqqlIfJiEQ7eIMj6kkOqWL+ro7BDMmi+pVSlE+Q2RmroY8pBKhFC7RsVW0JEjJ2OU4GqrVlxTncMNsfKNDCU3BXpWAU=
