language: ruby
rvm:
  - 2.2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
bundler_args: "--jobs=2"
cache: bundler
before_install:
  - gem install bundler --no-document
script: bundle exec rspec
branches:
  only:
    - master
notifications:
  email: false
  slack:
    secure: HKvrZjP1KUWhyNMA/3TfIe7vGXARu0gZFnntYPpIGm0N3Y8o3IHBc0Z0cY6N/VpFLinA95mfG8fk6SWUyqqlIfJiEQ7eIMj6kkOqWL+ro7BDMmi+pVSlE+Q2RmroY8pBKhFC7RsVW0JEjJ2OU4GqrVlxTncMNsfKNDCU3BXpWAU=
matrix:
  allow_failures:
    - rvm: ruby-head
  include:
    - rvm: 2.6
      env: RUBYOPT="--jit"
    - rvm: ruby-head
      env: RUBYOPT="--jit"
sudo: false
